### ISSUE TITLE
Q: Could this be used to animate css grid?

### ISSUE THREAD

**Issue by rchrdnsh** [micha-lmxt/svelte-motion#1]
I'm currently using animate-css-grid the library to animate position changes on a grid in a svelte/kit app... could this library potentially do the same? And thank you for making this :-)

**Comment by micha-lmxt** [comment]
I believe that should be possible with AnimateSharedLayout (see the [example here](https://svelte-motion.gradientdescent.de/layout) ).

**Comment by micha-lmxt** [comment]
I need an example to test and demonstrate the 'crossfade' prop (like [here](https://codesandbox.io/embed/framer-motion-animatesharedlayout-app-store-demo-i1kct?codemirror=1) anyway, so I'll try to work out a REPL soon.

**Comment by micha-lmxt** [comment]
REPL: https://svelte.dev/repl/c5e0a13a08c24a7fa60b6e6ade0faccf?version=3.38.2

**Comment by rchrdnsh** [comment]
Very nice...I'll close it out, but this is nice to have as a reference, for sure :-)

Thank you!
