### ISSUE TITLE
Lifecycle animation example

### ISSUE THREAD

**Issue by arjarn** [micha-lmxt/svelte-motion#2]
Could you explain how using lifecycle animation : start / end ?
I wanna make slideshow like your example but with preloading next slide when actual slide transition is done.

Thanx for your great job.

**Comment by micha-lmxt** [comment]
Hi, preloading make a lot of sense for the slideshow. I know that documentation could be more elaborate at this point. 

I've added a section for animation controls  and lifecycles to the [animation page](https://svelte-motion.gradientdescent.de/animation/#AnimationControls), which also have examples with REPL. Also you can look into `animate` on the [utility page](https://svelte-motion.gradientdescent.de/utilities). It also has some lifecycle callbacks and the documentation has improved. 

Finally, there is the documentation for [framer-motion](https://www.framer.com/motion/), most feature should transfer well.

Let me know if this helps

**Comment by arjarn** [comment]
It's perfect 👍 
I'm closing this issue and thanx again for your job.
