### ISSUE TITLE
ERROR: Cannot read properties of undefined (reading 'update')

### ISSUE THREAD

**Issue by rchrdnsh** [micha-lmxt/svelte-motion#25]
getting the following error simply trying to use motion in a kit app...did not change any code:

```js
[HMR][Svelte] Unrecoverable HMR error in <MotionConfig>: next update will trigger a full reload
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'update')
    at scaleCorrection (MotionConfigScaleCorrection.js:32:34)
    at instance (MotionConfig.svelte? [sm]:46:28)
    at init (index.mjs:1891:11)
    at new MotionConfig (MotionConfig.svelte? [sm]:49:30)
    at createProxiedComponent (svelte-hooks.js?v=c273ae18:341:9)
    at new ProxyComponent (proxy.js?v=c273ae18:242:7)
    at new Proxy<MotionConfig> (proxy.js?v=c273ae18:349:11)
    at create_if_block_2 (Grid.svelte? [sm]:235:64)
    at create_fragment (Grid.svelte? [sm]:250:67)
    at init (index.mjs:1906:37)
```

...which is completely breaking the use of svelte-motion for me in the latest version of kit, which is 480 at the time of this issue creation.

**Comment by micha-lmxt** [comment]
I started a new sveltekit app from the template today. I tried basic motion and some layout effects and both worked. Sveltekit version is "1.0.0-next.483", but I also downgraded to "1.0.0-next.480" without problems. Do you have a little more information, since there seems to be no general problem with sveltekit?

**Comment by rchrdnsh** [comment]
ok, so i did the same thing...

1. made a new svelte todo app using `npm create svelte@latest`
2. installed svelte-motion using `npm install --save-dev svelte-motion`
3. copied and pasted this example into a new svelte page:

https://svelte.dev/repl/4cbff886878c4b59beda7a1e0108c233?version=3.38.2

...and it worked just fine.

I then copied this REPL into the same page, completely replacing the other example:

https://svelte.dev/repl/0f586143c38f4a2599e5f3fbf9789ec3?version=3.38.2

...and immediately got the following error:

<img width="625" alt="Screen Shot 2022-09-16 at 9 33 55 AM" src="https://user-images.githubusercontent.com/7884263/190687015-c5ef2f65-5f78-4da9-98b3-8837871a0f88.png">

...in text form:

```bash
[HMR][Svelte] Unrecoverable HMR error in <Measure>: next update will trigger a full reload
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'update')
    at instance (Measure.svelte:102:34)
    at init (index.mjs:1892:11)
    at new Measure (Measure.svelte:75:46)
    at createProxiedComponent (svelte-hooks.js?v=42b7b71c:341:9)
    at new ProxyComponent (proxy.js?v=42b7b71c:242:7)
    at new Proxy<Measure> (proxy.js?v=42b7b71c:349:11)
    at create_fragment (MeasureContextProvider.svelte:12:43)
    at init (index.mjs:1907:37)
    at new MeasureContextProvider (MeasureContextProvider.svelte:16:27)
    at createProxiedComponent (svelte-hooks.js?v=42b7b71c:341:9)
```

...which I think is the same or similar error I was running into with the OP...I also found out that svelte-motion DOES INDEED work in production, so I'm running into the error in development mode...

**Comment by rchrdnsh** [comment]
hmmmm...I fully deleted `svelte-motion` and reinstalled it from the command line and it finally installed `0.11.3` and now I'm getting these errors everywhere on every page and nothing using svelte-motion seems to work...

<img width="576" alt="Screen Shot 2022-09-16 at 10 08 42 AM" src="https://user-images.githubusercontent.com/7884263/190692428-4f85bc83-1b01-43a6-babf-a9dc62ccd061.png">

**Comment by micha-lmxt** [comment]
Sounds like a HMR issue, does a full page reload (F5) help?

**Comment by rchrdnsh** [comment]
every full page reload produces the same error for me. This is essentially making the entire app unusable at this point...

This is the code at line 102 in the `Motion.svelte` file, if this helps at all:

```
    scaleCorrectionParentContext.update((v) =>
        v.concat([{
            updater,
            afterU
        } ])
    );
    afterUpdate(afterU);
```

...been trying to figure things out, but I admittedly don't know the codebase for either svelte/kit or svelte-motion, so I'm kind of fumbling in the dark...

**Comment by rchrdnsh** [comment]
looking to see if i can disable HMR in vite or kit ATM...

**Comment by rchrdnsh** [comment]
Tried doing this in the `vite.config.js` file, but still getting the same errors:

```js
const config = {
  server: {
    hmr: false
  },
```

**Comment by micha-lmxt** [comment]
Thank you, I was able to replicate the error. Quick fix is to change the import from 
`import  Motion from 'svelte-motion/src/motion/MotionSSR.svelte';`
to 
`import {Motion} from 'svelte-motion';`

I try to fix the SSR component in the meantime. Sveltekit has become quite robust, there seems to be no need for special Server-/Clientside-handling anymore. It is still needed for REPL at this point.

**Comment by rchrdnsh** [comment]
yay, that is indeed working for me now, thank you!

This also seems like a good thing now, yes? The ideal situation would be to not have to import an maintain a separate SSR component, correct?

Anyway, it is indeed working for me now, so thank you very much :-)
