### ISSUE TITLE
Getting odd warning? svelte is the type in package.json?

### ISSUE THREAD

**Issue by rchrdnsh** [micha-lmxt/svelte-motion#26]
Got this in the terminal while using svelte-motion:

```zsh
▲ [WARNING] "svelte" is not a valid value for the "type" field [package.json]

    node_modules/svelte-motion/package.json:34:10:
      34 │   "type": "svelte",
         ╵           ~~~~~~~~

  The "type" field must be set to either "commonjs" or "module".
```
...I looked at the `package.json` and it indeed says `svelte` for the type...is that what is supposed to be done?

**Comment by micha-lmxt** [comment]
Yes, that is a relict from the early days of Sveltekit. I changed it in the newest version today.

**Comment by rchrdnsh** [comment]
ok, great.
