### ISSUE TITLE
Issue with SvelteKit - Uncaught (in promise) Error: Function called outside component initialization

### ISSUE THREAD

**Issue by davidwparker** [micha-lmxt/svelte-motion#4]
Currently I have a component that has all of this copy+pasted:
https://svelte.dev/repl/b75f171a22f941689eac8b4e5e4b4e54?version=3.38.2

only things I changed were the imports:
```javascript
  import Motion from 'svelte-motion/src/motion/MotionSSR.svelte';
  import { useTransform } from 'svelte-motion/src/value/use-transform.js';
  import { useMotionValue } from 'svelte-motion/src/value/use-motion-value.js';
```

Then in SvelteKit, in a route, I import that component and try to render it. 

```html
<script>
  import UseMotionValueExample from '$lib/components/motion/UseMotionValueExample.svelte';
</script>

<UseMotionValueExample />
```

When I do, it results in this error:

```
Uncaught (in promise) Error: Function called outside component initialization
    at get_current_component (index.mjs:649)
    at onDestroy (index.mjs:662)
    at useCombineMotionValues (use-combine-values.js:26)
    at useTransform (use-transform.js:37)
    at instance (UseMotionValueExample.svelte:9)
    at init (index.mjs?v=96fea512:1485)
    at new UseMotionValueExample (UseMotionValueExample.svelte:17)
```

Any suggestions?

The library seems to work fine for other examples, but the `useX` ones don't work (note I only tried useAnimation() as well: https://svelte.dev/repl/1acf84b1db8f4eb38512fc05da8b42c6?version=3.38.2)

**Comment by micha-lmxt** [comment]
Hi,

SvelteKit is a bit of a pain for library maintainers... The issue you describe does not occur in vanilla Svelte nor in Sapper. But anyway, the error message suggests that the deferred 'onDestroy' call doesn't work as expected. It makes sense to make motion values less dependent on component lifecycles. I implemented something like the startStopNotify feature of Svelte stores.

Long story short: please try with version ^0.11.2

**Comment by davidwparker** [comment]
@micha-lmxt - whatever it was you fixed, worked! Thanks again!
